-- init-db.sql
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts;

GRANT CONNECT ON DATABASE data_jobs TO pipeline_user;

GRANT USAGE, CREATE ON SCHEMA raw     TO pipeline_user;
GRANT USAGE, CREATE ON SCHEMA staging TO pipeline_user;
GRANT USAGE, CREATE ON SCHEMA marts   TO pipeline_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA raw     TO pipeline_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA staging TO pipeline_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA marts   TO pipeline_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pipeline_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA staging
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pipeline_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA marts
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pipeline_user;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA raw     TO pipeline_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA staging TO pipeline_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA marts   TO pipeline_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw
    GRANT USAGE, SELECT ON SEQUENCES TO pipeline_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA staging
    GRANT USAGE, SELECT ON SEQUENCES TO pipeline_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA marts
    GRANT USAGE, SELECT ON SEQUENCES TO pipeline_user;
