CREATE TABLE IF NOT EXISTS raw.data_jobs (
    id                    SERIAL PRIMARY KEY,
    job_title_short       TEXT,
    job_title             TEXT,
    job_location          TEXT,
    job_via               TEXT,
    job_schedule_type     TEXT,
    job_work_from_home    BOOLEAN,
    search_location       TEXT,
    job_posted_date       TIMESTAMP,
    job_no_degree_mention BOOLEAN,
    job_health_insurance  BOOLEAN,
    job_country           TEXT,
    salary_rate           TEXT,
    salary_year_avg       NUMERIC,
    salary_hour_avg       NUMERIC,
    company_name          TEXT,
    job_skills            TEXT[],
    job_type_skills       JSONB,
    loaded_at             TIMESTAMP DEFAULT NOW()
);
